version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: diskord_db
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - net
    volumes:
      - diskord_db:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: diskord
    container_name: diskord_app
    command: bundle exec rails server -p 3000 -b 0.0.0.0 
    environment:
      - RAILS_ENV=development
      - DB_HOST=diskord_db
      - DB_PORT=5432
      - DB_PASSWORD=password
    networks:
      - net
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: diskord_ui
    container_name: diskord_frontend
    command: npm run start
    volumes:
      - ./frontend:/app/frontend
      - ./app/assets/javascripts/:/app/app/assets/javascripts/

networks:
  net:
volumes:
  diskord_db: